# Generated by Django 3.0 on 2021-09-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': 'Actor'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'Director'},
        ),
        migrations.AlterModelOptions(
            name='film_company',
            options={'verbose_name_plural': 'Film Company'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Movie'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, help_text='เรื่องย่อ', null=True),
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Movie')),
            ],
            options={
                'verbose_name_plural': 'Movie Comment',
                'ordering': ['id'],
            },
        ),
    ]
