# Generated by Django 3.0 on 2021-09-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movieimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='movieimage',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_preview',
            field=models.ManyToManyField(blank=True, to='movie_app.MovieImage'),
        ),
    ]
